[package]
name = "hangsound"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ws = "0.9.1"

[[bin]]
name = "httpserver"
path = "src/httpserver.rs"

[[bin]]
name = "wsserver"
path = "src/wsserver.rs"